version: 0.0
os: linux
files:
  - source: index.php
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: apache
    mode: 755
    type:
      - file
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: apache
    mode: 644
    type:
      - directory   
hooks:
    BeforeInstall:
      - location: scripts/remove.sh 
